<a href="https://colab.research.google.com/github/hadokan/python_basics/blob/main/pyhton_numpyXD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
# Multidimensional array with 2 rows and 5 columns
import numpy as np

arrayX2 = np.array([[0, 2, 3, 4,9],
                  [2, 6, 7, 8,0]])

print(arrayX2)

print('............')

print(arrayX2[1,:])
print(arrayX2[:,2])
print(arrayX2[1,2])

[[0 2 3 4 9]
 [2 6 7 8 0]]
............
[2 6 7 8 0]
[3 7]
7


In [19]:
import numpy as np
# A 3D array with 2 "slices", each of 3 rows and 4 columns
arrayX3 = np.array([[[0, 2, 4, 6],
                [1, 3, 5, 7],['A', 'B', 'C', 'D']],

                [[9, 11, 13, 15],
                 [8, 10, 12, 14],['E', 'F', 'G', 'H']]])

print(arrayX3)

print('...............')
print(arrayX3[:,:,1])
print('...............')
print(arrayX3[:,1,:])
print('...............')
print(arrayX3[1,:,:])
print('...............')
print(arrayX3[0,2,3])
print('...............')
print(arrayX3[1,2,3])
print('...............')
print(arrayX3[0,1,3])
print('...............')
print(arrayX3[1,1,3])

[[['0' '2' '4' '6']
  ['1' '3' '5' '7']
  ['A' 'B' 'C' 'D']]

 [['9' '11' '13' '15']
  ['8' '10' '12' '14']
  ['E' 'F' 'G' 'H']]]
...............
[['2' '3' 'B']
 ['11' '10' 'F']]
...............
[['1' '3' '5' '7']
 ['8' '10' '12' '14']]
...............
[['9' '11' '13' '15']
 ['8' '10' '12' '14']
 ['E' 'F' 'G' 'H']]
...............
D
...............
H
...............
7
...............
14


In [25]:
# 3D array with dimensions 4x5x3 filled with zeros
arrayZ = np.zeros((2, 5, 3))
print('...............')
print(arrayZ)

# check the dimension of arrayZ
print(arrayZ.ndim)

# total number of elements in arrayZ
print(arrayZ.size)

# results a tuple that gives the size of array in each dimension
print(arrayZ.shape)

# the data type of arrayZ
print(arrayZ.dtype)

# the memory address of arrayZ
print("Data of arrayZ is: ",arrayZ.data)

...............
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
3
30
(2, 5, 3)
float64
Data of arrayZ is:  <memory at 0x7e5d195ba980>
