<a href="https://colab.research.google.com/github/hadokan/python_basics/blob/main/pyhton_numpy1D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# A list named listX is created.
listX = [0, 1, 2, 3, 4, 5]

# use numpy to have an array using listX
arrayX = np.array(listX)

print(arrayX)

# An array with 5 elements filled with zeros
arrayZ = np.zeros(5)

print(arrayZ)


# An array with values from 0 to 6
arrayA = np.arange(7)

print("Using np.arange(7):", arrayA)

# An array with values from 1 to 19 with a step of 3
arrayB = np.arange(1, 20, 3)

print("Using np.arange(1, 20, 3):",arrayB)

# An array of 5 random numbers
arrayR = np.random.rand(5)

print(arrayR)

# An empty array of length 5
arrayE = np.empty(6)

print(arrayE)

[0 1 2 3 4 5]
[0. 0. 0. 0. 0.]
Using np.arange(7): [0 1 2 3 4 5 6]
Using np.arange(1, 20, 3): [ 1  4  7 10 13 16 19]
[0.10306963 0.24066656 0.74143862 0.76286497 0.15633189]
[0.0e+000 4.9e-324 9.9e-324 1.5e-323 2.0e-323 2.5e-323]


In [ ]:
import numpy as np

# An array of integers
int_array = np.array([0, 1, 3, 5])

# convert data type of int_array to float
float_array = int_array.astype('float')

# print the arrays and their data types
print(int_array, int_array.dtype)
print(float_array, float_array.dtype)

[0 1 3 5] int64
[0. 1. 3. 5.] float64


In [ ]:
import numpy as np

# A numpy array
numbers = np.array([0, 1, 3, 5, 7, 9])

# modify elements from index 3
numbers[3:] = 99
print(numbers)

# modify the first 3 elements
numbers[:2] = 10

print(numbers)

[ 0  1  3 99 99 99]


In [3]:
import numpy as np

arrayX = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9 ])

# reshape a 1D array as a 2D array (2 rows and 5 columns)
arrayXr = np.reshape(arrayX, (2, 5))
print(arrayXr)

result = np.reshape(arrayXr, (1, 10))
print(result)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4 5 6 7 8 9]]
