<a href="https://colab.research.google.com/github/hadokan/python_basics/blob/main/python_numpy_files.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

arrayX = np.array([[1,2, 3, 4],
                  [5,7, 11, 12]])

# save the array to a file
np.save('fileX.npy', arrayX)

In [4]:

import os
print(os.getcwd())
os.listdir()

/content


['.config', 'file1.npy', 'fileX.npy', 'sample_data']

In [5]:
# load the saved NumPy array
loaded_arrayX = np.load('fileX.npy')

# display the loaded array
print(loaded_arrayX)

[[ 1  2  3  4]
 [ 5  7 11 12]]


In [6]:
import numpy as np

# create two NumPy arrays
arrayA = np.array([0, 2, 4])
arrayB = np.array([1, 3, 5])

# save the two arrays into a single file
np.savez('fileAB.npz', file1 = arrayA, file2 = arrayB)

In [8]:
# load the saved arrays
load_dataX = np.load('fileAB.npz')

# retrieve the arrays using their names
arrayAe = load_dataX['file1']
arrayBe = load_dataX['file2']

# display the loaded arrays
print(arrayAe)
print(arrayBe)

[0 2 4]
[1 3 5]


In [9]:
import numpy as np

# get the current date and time
result = np.datetime64('now')

print("Current date and time:")
print(result)

Current date and time:
2023-08-17T12:10:52


In [12]:
date_today = np.datetime64('today', 'D')

print("Date:",date_today)


Date: 2023-08-17


In [16]:
import numpy as np
from datetime import datetime

# create a datetime64 object
#dt64 = np.datetime64('2023-01-30x09:11:12')
#ValueError: Error parsing datetime string "2023-01-30x09:11:12" at position 10
dt64 = np.datetime64('2023-01-30T09:11:12')

# convert datetime64 to datetime object
dt = dt64.astype(datetime)

# print the datetime object
print(dt)

2023-01-30 09:11:12


In [19]:
import numpy as np

# create a range of dates from 2023-01-01 to 2023-03-01
dates = np.arange('2023-01-01', '2023-03-02', dtype='datetime64[D]')

# print the dates
print(dates)

['2023-01-01' '2023-01-02' '2023-01-03' '2023-01-04' '2023-01-05'
 '2023-01-06' '2023-01-07' '2023-01-08' '2023-01-09' '2023-01-10'
 '2023-01-11' '2023-01-12' '2023-01-13' '2023-01-14' '2023-01-15'
 '2023-01-16' '2023-01-17' '2023-01-18' '2023-01-19' '2023-01-20'
 '2023-01-21' '2023-01-22' '2023-01-23' '2023-01-24' '2023-01-25'
 '2023-01-26' '2023-01-27' '2023-01-28' '2023-01-29' '2023-01-30'
 '2023-01-31' '2023-02-01' '2023-02-02' '2023-02-03' '2023-02-04'
 '2023-02-05' '2023-02-06' '2023-02-07' '2023-02-08' '2023-02-09'
 '2023-02-10' '2023-02-11' '2023-02-12' '2023-02-13' '2023-02-14'
 '2023-02-15' '2023-02-16' '2023-02-17' '2023-02-18' '2023-02-19'
 '2023-02-20' '2023-02-21' '2023-02-22' '2023-02-23' '2023-02-24'
 '2023-02-25' '2023-02-26' '2023-02-27' '2023-02-28' '2023-03-01']


In [22]:
import numpy as np

# today
today = np.datetime64('today')

# add tree day to today's date
todayp3 = today + np.timedelta64(3, 'D')

# create datetime64 objects for two dates
date1 = np.datetime64('2023-01-10')
date2 = np.datetime64('2023-01-15')

# calculate the number of days between the two dates
num_days = date2 - date1

# display the results
print("Today's date:", today)
print("After three days later:", todayp3)
print("Number of days between", date1, "and", date2, "is", num_days)

Today's date: 2023-08-17
After three days later: 2023-08-20
Number of days between 2023-01-10 and 2023-01-15 is 5 days


In [24]:
import numpy as np

# Define Two dates
dateA = np.datetime64('2023-01-01')
dateB = np.datetime64('2023-01-13')

# calculate the number of business days between the two dates
totalnumberof_bdays = np.busday_count(dateB, dateA)

# show result
print("Number of business days between", dateA, "and", dateB, "is", totalnumberof_bdays)

Number of business days between 2023-01-01 and 2023-01-13 is -9
