<a href="https://colab.research.google.com/github/hadokan/python_basics/blob/main/python_numpy_funct.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Let we have a NumPy array
arrayZ1 = np.array([[1, 2, 4],
                   [0, 3, 0]])

arrayZ2 = np.array([[0, 1, 0],
                   [2, 0, 3]])

# save the array to a file
np.save('fileZ.npy', arrayZ1)

# save the array to a file
np.savetxt('fileZ.txt', arrayZ2)

In [ ]:
import numpy as np
# load the saved NumPy array
load_arrayZ1 = np.load('fileZ.npy')

# display the loaded array
print(load_arrayZ1)

# load the saved NumPy array
loaded_arrayZ2 = np.loadtxt('fileZ.txt')

# display the loaded array
print(loaded_arrayZ2)



[[1 2 4]
 [0 3 0]]
[[0. 1. 0.]
 [2. 0. 3.]]


In [1]:
import os
print(os.getcwd())
os.listdir()

/content


['.config', 'sample_data']

In [ ]:

# Write line to file
with open('/content/Example2.txt', 'w') as writefile:
    writefile.write("This is line A")

In [4]:
import numpy as np

# Random integer from 0 to 99
random_intergers = np.random.randint(0, 100)

print(random_intergers)

# Random float-point number between 0 and 1
random_bwt01 = np.random.rand()

print(random_bwt01)


22
0.8169063876896235


In [5]:
import numpy as np

# An array of 11 random integers between 0 and 100
random_integer_array = np.random.randint(0, 100, 11)

print("Random Integer Array:\n",random_integer_array)

# An array of 5 random numbers between 0 and 1
random_float_array = np.random.rand(5)

print("\n1D Random Float Array:\n",random_float_array)

# 2D array of shape (5, 3) with random integers
result = np.random.randint(0, 10, (5,3))

print("\n2D Random Integer Array:\n",result)

Random Integer Array:
 [97 90 60 37 60 45 10 30 67 25 85]

1D Random Float Array:
 [0.22936609 0.76193708 0.73652608 0.85224577 0.66975883]

2D Random Integer Array:
 [[6 7 1]
 [5 4 5]
 [2 0 0]
 [2 1 5]
 [3 6 8]]


In [7]:
import numpy as np

# An array of integers from 0 to 9
arrayX = np.array([0,1,2,3,4,5,6,7,8,9])

# choose a random number from arrayX
random_choice = np.random.choice(arrayX)

print(random_choice)

7
