<a href="https://colab.research.google.com/github/hadokan/python_basics/blob/main/python_modules_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
# import module and rename it as
import math as mt
print(mt.pi)

3.141592653589793


In [19]:
# import only pi from math module
from math import pi
print(pi)

3.141592653589793


In [20]:
# import all names from the standard module math
from math import *

In [21]:
import numpy as np
# Program to multiply two matrices using nested loops
# 3x3 matrix
X = [[0,1,3],
    [4 ,4,7],
    [0 ,2,9]]
# 3x4 matrix
Y = [[0,3,1,2],
    [6,9,3,0],
    [0,2,2,1]]

# result is 3x4
result = [[0,0,0,0],
         [0,0,0,0],
         [0,0,0,0]]

# iterate through rows of X
for i in range(len(X)):
   # iterate through columns of Y
   for j in range(len(Y[0])):
       # iterate through rows of Y
       for k in range(len(Y)):
           result[i][j] += X[i][k] * Y[k][j]

for r in result:
    print(r)

print('........NUMPY RESULT (matmul)...........')
Z = np.matmul(X,Y)
print(Z)
print('........NUMPY RESULT (dot)...........')
Zx = np.dot(X,Y)
print(Zx)

#%timeit np.matmul(X,Y)
#%timeit np.dot(X,Y)

[6, 15, 9, 3]
[24, 62, 30, 15]
[12, 36, 24, 9]
........NUMPY RESULT (matmul)...........
[[ 6 15  9  3]
 [24 62 30 15]
 [12 36 24  9]]
........NUMPY RESULT (dot)...........
[[ 6 15  9  3]
 [24 62 30 15]
 [12 36 24  9]]


In [25]:
import numpy as np
# 1x4 vector
X = [0,1,3,2]
# 1x4 vector
Y = [0,3,1,4]
print('Inner Product')
Zi = np.inner(X,Y)
print(Zi)
Zo = np.outer(X,Y)
print('Outher Product')
print(Zo)

Inner Product
14
Outher Product
[[ 0  0  0  0]
 [ 0  3  1  4]
 [ 0  9  3 12]
 [ 0  6  2  8]]


In [24]:
#Element-Wise Multiplication (Hadamart Product)
# 3x3 matrix
X = [[0,1,3],
    [4 ,4,7],
    [0 ,2,9]]
# 3x3 matrix
Y = [[0,3,1],
    [6,9,3],
    [0,2,2]]

Ze=np.array(X)*np.array(Y)
print('Element-Wise Multiplication (Hadamart Product)')
print(Ze)

%timeit Ze=np.array(X)*np.array(Y)

Element-Wise Multiplication (Hadamart Product)
[[ 0  3  3]
 [24 36 21]
 [ 0  4 18]]
5.97 µs ± 2.2 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)
