<a href="https://colab.research.google.com/github/hadokan/python_basics/blob/main/python_numpy_funct.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Let we have a NumPy array
arrayZ1 = np.array([[1, 2, 4],
                   [0, 3, 0]])

arrayZ2 = np.array([[0, 1, 0],
                   [2, 0, 3]])

# save the array to a file
np.save('fileZ.npy', arrayZ1)

# save the array to a file
np.savetxt('fileZ.txt', arrayZ2)

In [ ]:
import numpy as np
# load the saved NumPy array
load_arrayZ1 = np.load('fileZ.npy')

# display the loaded array
print(load_arrayZ1)

# load the saved NumPy array
loaded_arrayZ2 = np.loadtxt('fileZ.txt')

# display the loaded array
print(loaded_arrayZ2)



[[1 2 4]
 [0 3 0]]
[[0. 1. 0.]
 [2. 0. 3.]]


In [ ]:
import os
print(os.getcwd())
os.listdir()

/content


['.config',
 'file1.npy',
 'Example2.txt',
 'fileZ.npy',
 'fileZ.txt',
 'sample_data']

In [ ]:

# Write line to file
with open('/content/Example2.txt', 'w') as writefile:
    writefile.write("This is line A")